#侧边栏设置
sidebar:
  #LOGO设置
  logo:
    avatar: '[config.avatar](/)'
  #主导航栏
  menu:
    website: '[官网](https://www.roidmc.com)'
    bbs: '[社区](https://bbs.roidmc.com)'
    wiki: '[Wiki](/)'
    status: '[状态监控](https://status.roidmc.com)'
    support: '[帮助中心](https://support.roidmc.com)'
 # Sidebar widgets
  widgets:
    index: [welcome, recent] # for home/wiki/categories/tags/archives/404 pages
    page: [welcome, toc] # for pages using 'layout:page'
    post: [toc, ghrepo] # for pages using 'layout:post'
    wiki: [ghrepo, toc, wiki_more] # for pages using 'layout:wiki'


#文章设置
article:
  # 如果没有指定封面，是否根据 tags 作为关键词搜索封面？
  auto_cover: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 200
  # 分类颜色
  category_color:
    '新闻稿': '#DA0F47'
  # 文章许可协议
  license: '本文采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  # 分享
  share:  [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    max_count: 5
    auto_cover: true # 如果没有封面就根据 tags 作为关键词搜索封面，开了此项将不会自动从文章中提取首张图片作为封面了。

#页脚设置
footer:
  social:
     qq:
       icon: '<img src="/wiki-assets/icon/qq-color.svg"/>'
       url: https://rmc.ink/social/qq
     github:
       icon: '<img src="/wiki-assets/icon/github-octocat.svg"/>'
       url: https://github.com/roidmc
     discord:
       icon: '<img src="/wiki-assets/icon/discord-color.svg"/>'
       url: https://rmc.ink/social/discord
     email:
       icon: '<img src="/wiki-assets/icon/email-color.svg"/>'
       url: mailto:support@roidmc.com
  sitemap:
     'Wiki':
       - '[近期](/)'
       - '[分类](/categories)'
       - '[标签](/tags)'
       - '[归档](/archives)'
     #'相关站点':
     #  - '[RoidMC官网](https://www.roidmc.com)'
     #  - '[BBS论坛](https://bbs.roidmc.com)'
     #  - '[建议反馈](https://feedback.roidmc.com)'
     #  - '[状态监控](https://status.roidmc.com)'
     #'友情链接':
     #  - '[申请友链](https://www.roidmc.com/contact-us)'
  content: | # 支持 Markdown 格式
    本站点所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
    本站由 [RoidMC Studios](/) 使用 [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) 主题创建，您可在 [Github](https://github.com/roidmc/wiki) 上找到本站源码。

# Local search 搜索功能
search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    field: post # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
  
