######## Stellar info ########
stellar:
  version: '1.25.0'
  homepage: 'https://xaoxuu.com/wiki/stellar/'
  repo: 'https://github.com/xaoxuu/hexo-theme-stellar'
  cdn_css: # Use cdn links instead of /css/main.css
  cdn_js: # Use cdn links instead of /js/main.js
  
# 侧边栏设置
# 左上角显示的 logo 区域，包含图标、大标题、副标题
logo:
  avatar: '[config.avatar](/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
  title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  subtitle: '' # '文字1 | 文字2' (鼠标放上去会切换到文字2)
menu:
  website: '[官网](https://www.roidmc.com)'
  bbs: '[社区](https://bbs.roidmc.com)'
  wiki: '[Wiki](/)'
  status: '[状态监控](https://status.roidmc.com)'
  support: '[帮助中心](https://support.roidmc.com)' 
######## Main ########
# 站点主结构树
site_tree:
  # 主页配置
  home:
    sidebar: search, welcome, recent, timeline

#文章设置
article:
  # 如果没有指定封面，是否根据 tags 作为关键词搜索封面？
  auto_cover: false # search from https://source.unsplash.com/
  # 封面图宽高比
  cover_ratio: 2.4
  # 如果没有指定横幅，是否根据 tags 作为关键词搜索横幅图片？
  auto_banner: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 200
  # 分类颜色
  category_color:
    '新闻稿': '#DA0F47'
  # 文章许可协议
  license: '本文采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  # 分享
  share:  [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    max_count: 5
    auto_cover: true # 如果没有封面就根据 tags 作为关键词搜索封面，开了此项将不会自动从文章中提取首张图片作为封面了。

#页脚设置
footer:
  social:
     qq:
       icon: '<img src="/wiki-assets/icon/qq-color.svg"/>'
       url: https://rmc.ink/social/qq
     github:
       icon: '<img src="/wiki-assets/icon/github-octocat.svg"/>'
       url: https://github.com/roidmc
     discord:
       icon: '<img src="/wiki-assets/icon/discord-color.svg"/>'
       url: https://rmc.ink/social/discord
     email:
       icon: '<img src="/wiki-assets/icon/email-color.svg"/>'
       url: mailto:support@roidmc.com
  sitemap:
     'Wiki':
       - '[近期](/)'
       - '[分类](/categories)'
       - '[标签](/tags)'
       - '[归档](/archives)'
     '相关站点':
       - '[RoidMC官网](https://www.roidmc.com)'
       - '[官方社区](https://bbs.roidmc.com)'
       - '[建议反馈](https://support.roidmc.com)'
       - '[状态监控](https://status.roidmc.com)'
     '友情链接':
       - '[申请友链](https://www.roidmc.com/contact-us)'
       - '[赞助我们](https://www.roidmc.com/donate)'
  content: | # 支持 Markdown 格式
    本站点所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
    本站由 [RoidMC Studios](/) 使用 [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) 主题创建，您可在 [Github](https://github.com/roidmc/wiki) 上找到本站源码。

# Local search 搜索功能
search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    field: post # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
  
