name: Wiki Deploy

on:
  push:
    branches: ["main", "next"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: wiki-deploy
  cancel-in-progress: false

jobs:
  build-and-deploy:
    if: contains(github.event.head_commit.message, '[actions skip]') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.WIKI_DEPLOY_KEY }}

      - name: Setup Git
        run: |
          git config --global user.email "106982374+RoidMC-Bot@users.noreply.github.com"
          git config --global user.name "roidmc-bot"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          git-config-name: "roidmc-bot"
          git-config-email: "106982374+RoidMC-Bot@users.noreply.github.com"
          ssh-key: ${{ secrets.WIKI_DEPLOY_KEY }}
          single-commit: true
          branch: gh-pages
          folder: .vitepress/dist
          clean: false
