name: Wiki Delpoy

# 触发条件: push到Main分支后自动触发
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Wiki Build & Delpoy
    # 使用Ubuntu-22.04作为编译部署环境
    runs-on: ubuntu-22.04 

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      # 设置Node.js环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 设置包缓存目录
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # 配置Hexo运行安装环境
      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.WIKI_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "106982374+RoidMC-Bot@users.noreply.github.com"
          git config --global user.name "roidmc-bot"
          npm install hexo-cli -g
          npm install

      #编译MarkDown文件 (预留) 
      #- name: Generate files
      #run: |
      #  hexo clean
      #  hexo generate

      # 部署Hexo至gh-pages分支下    
      - name: Deploy
        run: |
          hexo clean
          hexo deploy
